//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace avtoServ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STOEntities : DbContext
    {
        public STOEntities()
            : base("name=STOEntities")
        {
        }

        private static STOEntities _context;
        public static STOEntities GetContext()
        {
            if (_context == null)
            {
                _context = new STOEntities();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avto> Avto { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Detail> Detail { get; set; }
        public virtual DbSet<FaultTypes> FaultTypes { get; set; }
        public virtual DbSet<RequestStatus> RequestStatus { get; set; }
        public virtual DbSet<Role_> Role_ { get; set; }
        public virtual DbSet<STObase> STObase { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
