//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace avtoServ
{
    using System;
    using System.Collections.Generic;
    
    public partial class STObase
    {
        public int request_id { get; set; }
        public Nullable<int> application_number { get; set; }
        public Nullable<System.DateTime> request_date { get; set; }
        public Nullable<int> ID_Clients { get; set; }
        public Nullable<int> ID_Avto { get; set; }
        public Nullable<int> fault_type_id { get; set; }
        public Nullable<int> ID_Detail { get; set; }
        public Nullable<int> ID_RequestStatus { get; set; }
    
        public virtual Avto Avto { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Detail Detail { get; set; }
        public virtual FaultTypes FaultTypes { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
    }
}
