//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace avtoServ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID_Users { get; set; }
        public string Login_ { get; set; }
        public string Password_ { get; set; }
        public Nullable<int> id_Role_ { get; set; }
    
        public virtual Role_ Role_ { get; set; }
    }
}
